---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-secret
  namespace: monitoring
spec:
  encryptedData:
    api_url: AgB+wDk9gsqCGhKsIU5SEXDLZBN1sTBzY2czVny54eWcRrvJkZHtS2KWGI8MozjAcDDm26Gn+y6v7VrnTgG5Ms/H9ah95qpJ9Rk8z7CAKTAPIoQUqWzJsvPy9+udY00cZmDhxrgvsYf5t1DfLKJ6/aInorBnsHg5PbLplLHPOkEwfvj5Abru7i79SCR9fE8yV25cuv+YV2jclIv8rxDXSd9lyDtqxibSyGGd67eRYJ20nmf5oGztyVL9bAKKXZKML1vtcFpjFcKWx9dVc77wCTbYgxjnQeAX7IhWu5zY9uyJCJ+e54RGot+k44puRUn2AnFq6Ls1vyi4QEZIt7Nb+Wu4DRvpbnd+5BGM5BdxSM4BWwpqwSVcra9nymrorx13769HoR95zdIG5hc4bmKKvPgDIITLvvRg/YIn0yXneGgBM41N+l2QIUXyqxB4kMPi8RECrykXkH4aIRy65CC/+EQ8eIgnigPFTOjPYPIpfbMRmq6q6TaVHMhjk8xr2BEm7/LjvN/jJPnCZA73oAwsqdVKTX68ZpqK9czeyjJbXNpNIeXj9zs8QljaTTcl9G9Ktmf4K5NQaZ/7HnZubH1K2oI+zxFaTXb4ysbfQEuTOMoQ6/QqUoOJP3Yh1eQkaLgMxr3sKRx+n16SA4lBIEVwmfwLHIAuFC/fYTsuQuP8+yZWx+EiriQ06gbUe0pAhoEAowuXH0UZCqux49PX9zigFQAh5G7cEQjqSOvDdP00t2Iytg94HTADVHoRUf1iXNg7dyjkl9oxuuzCfZCyorfE1Z4UnJ5AU2G/BRuGdSqG9NRBNlg=
  template:
    metadata:
      name: slack-webhook-secret
      namespace: monitoring
