apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitnest-frontend
  namespace: fitnest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 957563772273.dkr.ecr.us-east-1.amazonaws.com/fitnest-frontend:v2
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"