name: Build and Push to AWS ECR

# This tells GitHub to run this pipeline every time you push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Docker Images and Push to ECR
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Authenticate securely with AWS using your GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Matches your Terraform region

      # 3. Log in to your private AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build and Push the Backend Image
      - name: Build, tag, and push Backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fitnest-backend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./simple-k8s-app/backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 5. Build and Push the Frontend Image
      - name: Build, tag, and push Frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fitnest-frontend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./simple-k8s-app/frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG